### ISSUE TITLE
center aligned images always floating to the left

### ISSUE THREAD

**Issue by Grandma-Betty** [flammy/imagebox#110] opened 2019-08-15 09:27 UTC
Using the following code, the image is always floating to the left when the image needs to be set in the middle of the page:
` [{{ :getting_started:tutorials:haltest1.png?300 | //Control system of the test program// }}]`
Edit: Using PHP 7.3 in case this information matters.

**Comment by DeadalusVIII** [comment] 2019-10-22 20:40
I have noticed this issue as well.

**DokuWiki version:** Release 2018-04-22b "Greebo"
**PHP version:** 7.3.5

I recently migrated from an rather old dokuwiki version (created around 2010) and back then I was already using this plugin (or at least one with the same name), so I noticed the difference.

**Comment by FabianDiTaranto** [comment] 2019-11-04 13:12
Still not fixed with version 2019-10-13.

**Comment by Schroeffu** [comment] 2020-04-24 13:42
Same here, still not fixed?

**Comment by alajovic** [comment] 2020-10-06 09:30
I made an attempt to fix this in my setup, and it seems to have succeeded. I did the following modification to `style.css`:

```patch
--- a/style.css
+++ b/style.css
@@ -2,7 +2,7 @@ div.thumb2 {
 margin-bottom:.5em;
 padding-right:10px;
 width:auto;
-display:table-cell
+display:block
 }
 
 div.trien {
```

Please try it out and let me know if it breaks something. If it turns out to work for others as well, I'll make a PR with this change.

**Comment by TZJinzo** [comment] 2020-11-22 03:32
Correct, this issue still exists.

**Comment by alajovic** [comment] 2020-11-30 23:23
@TZJinzo have you tried my patch above? Did it work?

**Comment by TZJinzo** [comment] 2020-11-30 23:41
Thank you so much for this. Indeed this has fixed the problem for it seems. This plugin was unusable before because you can't centre images and it made workflow impossible for my team wiki. See results below as example. For people who are less experienced at Doku, the style.css file to be modified is here: /public_html/lib/plugins/imagebox/style.css

![image](https://user-images.githubusercontent.com/29394079/100678573-67bbb380-3365-11eb-9ff4-8b501a05741b.png)

**Comment by alajovic** [comment] 2020-12-01 00:04
Okay, let's just go forward with a PR, then. There are at least two confirmed cases where my patch helped, and nobody screamed about any breakage yet, so... ship iiit! :D

**Comment by TZJinzo** [comment] 2020-12-01 02:02
Thank you so much for this! This plugin helps a huge amount for many people and this fix finally allows it to be fully functional. Sorry as an aside, will this work fully with the rename page plugin?

**Comment by urapadmin** [comment] 2021-09-11 13:06
yes, thanks a bunch. This solved the issue for me, too. And I cannot see any unfortunate side-effects, so far.

**Comment by flammy** [comment] 2023-08-13 08:06
thank you for your contributions, your pr is merged.

**Closed by flammy** 2023-08-13 08:06 UTC
